version: "3"

services:
  postgres:
    image: postgres:9.6.16-alpine
    ports:
      - '5432:5432'

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
